version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.4
    steps:
      - checkout
      - run:
        name: install dependencies
        command: yarn install
      - run:
        name: build
        command: yarn build